### ISSUE TITLE
[Feature Request] Add support for automatically using workspace TypeScript version

### ISSUE THREAD

**Issue by jordangarcia** [yioneko/vtsls#134]
Hi!  Just wanted to say I'm really enjoying vtsls as a typescript wrapper with Neovim!  Its the first thing that has felt as fast and feature rich as vscode.

One issue that I am having is that I work in a multi project repo (yarn workspace) that uses different versions of typescript for different `packages/<project>`s.  It would be great if there was a way that I could do any of the following.

1. Be able to call a command to `select workspace version` in `on_attach` without having it prompt which one to use.  
2. Be able to pass something like 

```
{
  settings = {
     vtsls = {
        typescript = {
           globalTsdk = "./node_modules/typescript/tsserver"
        }
     }
  }
```

3. Or have some option that's like `automaticallyUseWorkspaceTypeScriptVersion`

I'm not super opinionated about how to solve it, it would just be awesome to have a way to be able to per project directory automatically set the typescript version.

VSCode kind of has a workaround for this by having the `userSettings` `typescript.tsdk` respected and trusted, where as it seems in like in `vtsls` the configuration `readGlobalTsdk` `inpspect` always returns the `workspaceValue` and never a `globalValue`.

`src/typescript-language-features/src/configuration/configuration.electron.ts`

```
      readGlobalTsdk(configuration) {
        const inspect = configuration.inspect("typescript.tsdk");
        if (inspect && typeof inspect.globalValue === "string") {
          return this.fixPathPrefixes(inspect.globalValue);
        }
        return null;
      }
```

If I am overlooking an easy way to do this please let me know, otherwise it would be awesome if this is something that could be supported.

Thanks!

**Comment by yioneko** [comment]
In VSCode, the selection in command `typescript.selectTypeScriptVersion` will be memoized and stored permanently on disk. LSP doesn't specify the support for permanent storage (the `vscode.Memento` feature), so we need another way to let user automatically select the exepected TypeScript version.

I added a config option `vtsls.autoUseWorkspaceTsdk` for this, you can test it by installing the alpha version of server `npm install -g @vtsls/languae-server@alpha`.

Regarding the `workspaceValue` vs. `globalValue` problem: by default, [the setting is assumed to be workspace-wide](https://github.com/yioneko/vtsls/blob/7f003323a8f50a392cb848643a7144a49637e9de/packages/service/src/shims/configuration.ts#L83-L89), since usually the user may change the configuration for different projects. LSP doesn't provide a way to differentiate whether an option is either global or local, so the `globalValue` is always assumed to be `undefined`.

**Comment by jordangarcia** [comment]
Awesome!  I will test this out soon. Thanks for the quick response

**Comment by jordangarcia** [comment]
Tested this out and it works well!  

Another question, is it possible to an autocmd and switch the configuration that is passed to `vtsls`.  I currently use `lspconfig` which abstracts this a bit away to the point I dont quite understand it.

Is there like a `workspace/configurationChange` event or some other LSP thing that can be sent when a neovim autocmd happens?

EIther way, this currently resolve my issue.  Thanks!

**Comment by yioneko** [comment]
Glad to hear the good news.

> Is there like a workspace/configurationChange event or some other LSP thing that can be sent when a neovim autocmd happens?

You can refer to the [workspace/didChangeConfiguration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration) notification.

**Comment by llllvvuu** [comment]
A cool feature could be to have this, but don't show the pop up when no workspace TypeScript is found (just silently use the fallback)
