### ISSUE TITLE
Usage with VSCode

### ISSUE THREAD

**Issue by jansedlon** [yioneko/vtsls#165]
Hello, is there a way to use this with vscode? I went through the readme but didn't find anything. Is it even possible? Or have i misunderstood the purpose of this package?

**Comment by yioneko** [comment]
Not sure what are you trying to do? VSCode uses its bundled TypeScript extension for intellisense, and the extension is also the source of the most of the code of this package. There is no support for VSCode and no need for that here. If you are looking for TypeScript support in VSCode, you can just follow its official guide. There is no much difference here since the package basically share the same related code with the VSCode extension.

**Comment by jansedlon** [comment]
Ahhh sorry, i though that since tsserver is not LSP compliant, this package wraps the package in order to be LSP compliant. Sorry!
