### ISSUE TITLE
vtsls diagnostics gives wrong errors in Neovim

### ISSUE THREAD

**Issue by jim-at-jibba** [yioneko/vtsls#172]
I am using this lsp in Neovim but it seems to give me incorrect diagnostics. 

For example, it will tell me in Neovim that there are unused @ts-expect-error directives but when I remove them the error that directive was covering now shows when running tsc in the terminal.

Does that make sense? Any ideas?

**Comment by yioneko** [comment]
Have you've tried `vtsls.autoUseWorkspaceTsdk = true`? By default the server use the bundled version of ts and that might be different from the version installed to your project, which is possibly used by tsc running in your terminal.

**Comment by jim-at-jibba** [comment]
Thanks for your speedy reply. That sounds like it could have been the issue but Im using LazyNvim and that is already set. I got excited for a minute.

**Comment by jim-at-jibba** [comment]
I was able to rectify the issue by downgrading my version of Neovim. I saw the issue in 0.10.0 but not in 0.9.5!

I dont understand why but there we go. Thanks for your help

**Comment by Daydreamer-riri** [comment]
Hi @yioneko, I ran into the same bug.
Look at the screenshot:
<img width="865" alt="{E09777CC-4ECA-47B4-A7EA-301BC769F59A}" src="https://github.com/user-attachments/assets/9ddaf572-13e9-49f7-9e11-fd70da9b28ef">

and then:
<img width="648" alt="{473F1A32-8FC3-463D-A80B-DF3B71D8DA17}" src="https://github.com/user-attachments/assets/ff275770-cfee-4455-9c75-8ecb83a2b836">

When I reopen the file:

<img width="885" alt="{B762A4D5-62F2-46B5-9D43-85493DB546EF}" src="https://github.com/user-attachments/assets/4217a5bb-c3f5-4070-9560-d8c822fd54d9">

> Have you tried vtsls.autoUseWorkspaceTsdk = true? 

I'm using lazyvim. lazyvim's default configuration for vtsls has autoUseWorkspaceTsdk as `true`. see: https://www.lazyvim.org/extras/lang/typescript#nvim-lspconfig

**Comment by yioneko** [comment]
@Daydreamer-riri Not much idea about this but providing client LSP logs (`:lua vim.lsp.set_log_level("DEBUG")`) for that would be helpful. We can look into `textDocument/didOpen` and `textDocument/publishDiagnostics` notifications to see if the issue comes from the server side.

My current guess is that this might be a issue related to typescript and you can test it in vscode to see if the results are the same. You can switch to the workspace version of typescript in vscode in `Command Palette -> TypesScript: Select TypeScript Version`.

**Comment by Daydreamer-riri** [comment]
vscode does not have the same error (I have been using vscode all my life and have never encountered a similar error)

This error occurs only in the `@ts-expect-error` comment.

**Comment by yioneko** [comment]
I'm pretty sure that the issue is on the server side now, but I do not have any clue regarding the case in your demo that the diagnostic report is different after the file reopening yet. Afaik the diagnostic computing of tsserver is deterministic and the server only does buffering for diagnostic fetching.

I tested `@ts-expect-error`comment with simple erroneous statements before but could not reproduce the problem, so I would like to get reproducible code example for this. If you are willing to provide this, you can extract the code example similar to this:

```typescript
type L = {}
type R = {}
const rhs: R = {}
// @ts-expect-error
const lhs: L = rhs;
```

**Comment by Daydreamer-riri** [comment]
I can't reproduce it for the example you gave. I will try to make a minimally reproducible example.

Also regarding your comment: “ the typescript version which can be found by looking at the full cmd of the running tsserver path.”, I'm not sure how this should be obtained?

**Comment by yioneko** [comment]
> I'm not sure how this should be obtained?

I think this could work on windows in powershell:
```powershell
wmic path win32_process get commandline | findstr tsserver
```
