### ISSUE TITLE
Syntax highlighting is not appearing.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [yioneko/vtsls#188]
I'm not sure if this is an issue with vtsls or the theme I'm specifically using. But in neovim when I use tsserver I get syntax highlighting thats provided by the lsp but when using vtsls I don't appear to be getting any meaningful syntax highlights. 

I couldn't seem to find anything in the readme or documentation relating to it. I used Mason to install vtsls and installed vtsls.nvim via lazy package manager.

Neovim: v0.10.0

**Comment by yioneko** [comment]
The highlighting provided by LSP is called [semantic highlighting](https://code.visualstudio.com/docs/typescript/typescript-editing#_syntax-highlighting-and-semantic-highlighting), it won't highlight the whole file but mark some tokens to have semantic information so that the editor could apply extra highlighting for them. It is likely that the "syntax highlighting" you mentioned should be provided by nvim treesitter, the semantic highlighting provided by LSP is just meant to enhance it.

In neovim, you could check whether the feature is working by the two commands:
- `:lua vim.treesitter.stop()` to disable the treesitter highlight
- `:syntax off` to disable the fallback vim builtin regex highlight

If you could see the remaining highlights on the file, move the cursor to it and execute `:Inspect`, it will output a list of `Semantic Tokens` and the corresponding highlight groups for the current token.

Otherwise you might want to check if the semantic tokens feature is working on the client `:h lsp-semantic_tokens`. Hope that you'll see it useful.

**Comment by Jas-SinghFSU** [comment]
I switched to a different configuration from my own and I think it was a misconfiguration on my part. Vtsls seems to be working perfectly now so I'm not sure what I configured wrong. Thank you for your guidance.
