### ISSUE TITLE
Document how to build locally

### ISSUE THREAD

**Issue by rchl** [yioneko/vtsls#25]
I've tried to quickly set up the project and I'm not entirely sure how to build it properly.

Tried:
1. Clone the project
2. `git submodule init && git submodule update`
3. `pnpm i`

At this point `pnpm build` fails with errors related to not being able to resolve `@vsc-ts`. I see that it's an alias defined in `tsconfig.json` but haven't figured out why it's not working.

Could you document in the readme how to build the project locally?

**Comment by yioneko** [comment]
Your build steps are correct but the resolution issue seems weird to me. Could you confirm that `typescript-language-features` actually exists under `packages/service/src`? Please remove that and run `pnpm --filter ./packages/service patch-extension` to see if the extension has been copied to `packages/service/src`.

I wrote some development steps before in readme but has removed that because the current workflow is not ideal and requires many manual works. But build steps are simple so only adding that is reasonable.

**Comment by rchl** [comment]
`packages/service/src/typescript-language-features` directory exists but is empty.

> Please remove that and run `pnpm --filter ./packages/service patch-extension` to see if the extension has been copied to `packages/service/src`.

```
Error: Command failed: cp /usr/local/workspace/github/vtsls/packages/service/vscode/extensions/typescript-language-features/package.json /usr/local/workspace/github/vtsls/packages/service/src/typescript-language-features/ -r
cp: -r is not a directory
```

**Comment by yioneko** [comment]
Thanks, it seems that using shell `cp` is not reliable. The temporary fix:
```diff
diff --git a/packages/service/scripts/patch.js b/packages/service/scripts/patch.js
index 85c39b1..3f8d33b 100644
--- a/packages/service/scripts/patch.js
+++ b/packages/service/scripts/patch.js
@@ -49,7 +49,9 @@ async function copyTsExtTo(targetDir) {
   for (const entry of await fs.readdir(tsExtDir)) {
     if (entry.match(/(src)|(package.*\.json)/)) {
       const entryPath = path.resolve(tsExtDir, entry);
-      await execFile("cp", [entryPath, `${targetDir}/`, "-r"]);
+      // await fs.copyFile(entryPath, targetDir);
+      const stat = await fs.stat(entryPath);
+      await execFile("cp", [entryPath, `${targetDir}/`].concat(stat.isDirectory() ? ["-r"] : []));
     }
   }
 }
```
The formal fix will be different to drop reliance on shell `cp`.
