### ISSUE TITLE
Testing server side filtering

### ISSUE THREAD

**Issue by KaranAhlawat** [yioneko/vtsls#52]
Continuing from https://github.com/joaotavora/eglot/discussions/1178, I have a local clone of the vtsls repo, have built it successfully and am using it with eglot currently. I have turned the event buffer back on to see what's going on.

I added the options specified in the PR (https://github.com/yioneko/vtsls/pull/50), although I'm unsure if I've added them correctly. Is there any way I can check from the server side if I'm it's setting the options correctly?

For now, these are the logs

```
(:processId 233525 :rootPath "/home/karan/Secondary/dev/vtsls-repo/" :rootUri "file:///home/karan/Secondary/dev/vtsls-repo" :initializationOptions
                      (:vtsls.experimental.completion.enableServerSideFuzzyMatching t :vtsls.experimental.completion.entriesLimit 50 :typescript.preferences.includePackageJsonAutoImports "off")
                      :capabilities
                      (:workspace
                       (:applyEdit t :executeCommand
                                   (:dynamicRegistration :json-false)
                                   :workspaceEdit
                                   (:documentChanges t)
                                   :didChangeWatchedFiles
                                   (:dynamicRegistration t)
                                   :symbol
                                   (:dynamicRegistration :json-false)
                                   :configuration t :workspaceFolders t)
```

Has been cut for brevity, as the options are specified up front.

**Comment by KaranAhlawat** [comment]
Now that I think about it that doesn't look like valid JSON. Will amend.

**Comment by yioneko** [comment]
The settings should be passed through `workspace/didChangeConfiguration`. `InitializationOptionos` is not used currently.

For eglot :
```elisp
(setq eglot-workspace-configuration
      '((vtsls (experimental (completion (enableServerSideFuzzyMatch . t)
                                           (entriesLimit . 200))))))
```

**Comment by KaranAhlawat** [comment]
All right! I think the issue has been resolved. The completions are smooth and fast, even with the events-buffer not being 0.

To use the options, I have set this in my `.dir-locals.el` file.

```
((nil
  . ((eglot-workspace-configuration
      . ((:vtsls (experimental (completion (enableServerSideFuzzyMatch . t)
                                           (entriesLimit . 200)))))))))
```

**Comment by KaranAhlawat** [comment]
Setting the variable with `setq` will not work btw, as this is a directory local variable that must be set per project for now.

**Comment by yioneko** [comment]
Thanks for your good news. I'm still a newbie for emacs so my setup could be wrong.

I have to remind that the two options should be considered experimental and the proper way is to oprimize the performance of client. It seems that eglot is one of the slowest LSP client I've tested, although I think it is probably mainly due to the performace of elisp interpreter. We cannot require every server to apply such a hack to help client with poor performance.

**Comment by KaranAhlawat** [comment]
In Eglot's defense, TypeScript language servers are the only ones that behave this way from all the languages I've seen. 

This is not due to the slowness of the Elisp interpreter I believe, since we even have native compilation at this point. 
I think it is more so the fact that Eglot does everything on the same thread, the main UI thread. That ends up taking a significant amount of time where the UI is not responsive.

Still, thank you for being so patient with my issues.
Will there be a new update to vtsls with these changes?

**Comment by yioneko** [comment]
> In Eglot's defense, TypeScript language servers are the only ones that behave this way from all the languages I've seen.

Yes, as far as I know, nearly every lsp client has an issue about typescript slowness. But there are also many servers using `tsserver` under the hood, such as `volar`, `svelte`, `astro`, etc, technically they all suffer from the same problem. Another usually complained server is `tailwind`, which also fill client with thousands of completion candidates.

> This is not due to the slowness of the Elisp interpreter I believe, since we even have native compilation at this point.

I have little knowledge about Elisp interpreter, maybe I could test native compilation to see its improvements. I see `lsp-mode` mentioned that in its doc but failed to find in eglot, so initially I think this feature needs some tweaking on application code but maybe I'm wrong. 

> I think it is more so the fact that Eglot does everything on the same thread, the main UI thread. That ends up taking a significant amount of time where the UI is not responsive.

Responsiveness is not equal to speed. Even the processing work is moved to a separate thread, the time cost could be hardly reduced and the delay still exists. In fact, other lsp clients like VSCode and nvim also do their work on ui thread but they are much faster than eglot on my machine. So I guess it's because the V8 (in VSCode) and luajit (in nvim) are more efficient than Elisp interpreter since the client code between them used for processing should be functionally similar.

> Will there be a new update to vtsls with these changes?

I'm still testing against this. A new release will be available when there are generally no remaining issues for it. Thanks for your testing :)

**Comment by KaranAhlawat** [comment]
Thank you for the responses! These are definitely points I should consider. I'm not super comfortable with topics such as concurrency, interpreter efficiency and the such, and even less so with Eglot and Emacs internals. But I see your points.

Since you will release a new update when you're satisfied with the testing, I will now be closing this issue.

**Comment by joaotavora** [comment]
Am I too late?  I the guy with some "knowledge on Eglot internals" that someone requested back in https://github.com/joaotavora/eglot/discussions/1178, but I don't fully understand what's being done here.  Are the server-optimizing options being passed correctly from the client to the server now?  Why aren't these speed-enhancing option values the default, btw?

**Comment by KaranAhlawat** [comment]
You're not too late, as the changes are yet to be released. Yes, the options are being passed correctly using workspace configurations. They are most likely not the default because not all editors need them.

**Comment by yioneko** [comment]
@joaotavora The motivation is that the server could respond thousands of completion entries to client, and if client is not good at processing such amount of entries, the completion will be laggy from user experience.

So the proposal here is to execute filtering on server side, before sent to client. Also allow client to limit number of entries to return, so that there is at least an upper bound of client processing time.

The two options are opt-in now because they are experimental and many clients don't need them as they can handle huge completion response within few millionseconds. In fact, I didn't feel that laggy experience until eglot, but I guess it's not fault of eglot but execuation performance of Elisp platform. Native compilation is an exciting idea, I may take it as a look.
